### ISSUE TITLE
Crashing when trying to launch corrupted plains

### ISSUE THREAD

**Issue by JollyGreenTank** [TheDeadGamer101/NewWorld-Mod#1]
I am using a LG G6 and get a "app has stopped responding" error when trying to launch the corrupted plains mission.

**Comment by matt847** [comment]
I use Asus and I have the same problem

**Comment by kapzduke** [comment]
The map file is corrupted. So is Wasteland's. (like cmon it has the name of an already existing map, a BUILT-IN one)

**Comment by matt847** [comment]
Thanks👍

Il ven 10 apr 2020, 23:59 kapzduke <notifications@github.com> ha scritto:
